=== Erkan-Yilmaz/just-another-tool-for-test-automation/jatta.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
#Just Another Tool for Test Automation
#Copyright (C) 2011  Marc Nesello
#
#This file is part of Just Another Tool for Test Automation.
#
#Just Another Tool for Test Automation is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

	<xsd:annotation>
		<xsd:documentation>
			Author: marcn
			XML Schema for the test list of JASTA.
			</xsd:documentation>
	</xsd:annotation>
	
	<xsd:complexType name="commandType">
	<xsd:sequence>
		<xsd:element name="path" type="xsd:string" minOccurs="1" maxOccurs="1"></xsd:element>
		<xsd:choice minOccurs="0" maxOccurs="unbounded">
			<xsd:element name="positiveCheck" type="xsd:string"></xsd:element>
			<xsd:element name="negativeCheck" type="xsd:string"></xsd:element>
			<xsd:element name="inputData" type="xsd:string"></xsd:element> 
		</xsd:choice>
	</xsd:sequence>	
		<xsd:attribute name="id" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" use="required"/>	
	</xsd:complexType>
	
	<xsd:complexType name="groupType">
		<xsd:sequence>
			<xsd:element name="command" type="commandType" minOccurs="1" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="parallel" type="xsd:unsignedInt" use="optional" default="1"/>	
		<xsd:attribute name="serial" type="xsd:unsignedInt" use="optional" default="1"/>	
		<xsd:attribute name="id" type="xsd:string" use="required" />
		<xsd:attribute name="name" type="xsd:string" use="required"/>	
	</xsd:complexType>
	
	<xsd:element name="testlist">
	    <xsd:complexType>
	        <xsd:sequence>
	        	<xsd:element name="test" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="head">
								<xsd:complexType>
									<xsd:sequence>
											<xsd:element name="group" type="groupType" minOccurs="0" maxOccurs="unbounded"/>		
									</xsd:sequence>
									<xsd:attribute name="warnIfFailed" type="xsd:unsignedInt" use="optional" default="0"/>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="body">
								<xsd:complexType>
									<xsd:sequence>
											<xsd:element name="group" type="groupType" minOccurs="1" maxOccurs="unbounded"/>							
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
							<xsd:element name="tail">
								<xsd:complexType>
									<xsd:sequence>
											<xsd:element name="group" type="groupType" minOccurs="0" maxOccurs="unbounded"/>							
									</xsd:sequence>
									<xsd:attribute name="warnIfFailed" type="xsd:unsignedInt" use="optional" default="0"/>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
						<xsd:attribute name="timeout" type="xsd:unsignedInt" use="required"/>
						<xsd:attribute name="id" type="xsd:ID" use="required" />
						<xsd:attribute name="name" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
	        </xsd:sequence>
	        <xsd:attribute name="name" type="xsd:string" use="required"/>
	        <xsd:attribute name="timeout" type="xsd:unsignedInt" use="required"/>
	        <xsd:attribute name="logfile" type="xsd:string" use="required"/>
	    </xsd:complexType>
    </xsd:element>
    
</xsd:schema>

=== Erkan-Yilmaz/just-another-tool-for-test-automation/example_win/runTester2_win.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
#Just Another Tool for Test Automation
#Copyright (C) 2011  Marc Nesello
#
#This file is part of Just Another Tool for Test Automation.
#
#Just Another Tool for Test Automation is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<testlist name="Beispieltest" timeout="0" logfile="runTester2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jatta.xsd">

  <test id="test2" name="App sleeps, wait till end" timeout="0">
<head>
</head>
    <body>
      <group parallel="1" serial="1" id="1" name="jattetest">
        <command id="2" name="JATTATester aufrufen">
        <path>java -cp "..\JATTATester\build\classes" jattatester.JattaTester</path>
        <inputData>n</inputData>
        <inputData>sleep</inputData>
		<inputData>5</inputData>
		<positiveCheck>Stopped after \d+ seconds</positiveCheck>
        <negativeCheck>(E|e)rror</negativeCheck>
        </command>
      </group>
    </body>
<tail></tail>
  </test>
  <test id="test3" name="App with some input" timeout="20">
<head>
</head>
    <body>
      <group parallel="1" serial="1" id="1" name="jattetest">
        <command id="2" name="JATTATester aufrufen">
        <path>java -cp "..\JATTATester\build\classes" jattatester.JattaTester</path>
        <inputData>y</inputData>
        <inputData>Marc</inputData>
		<inputData>23</inputData>
		<positiveCheck>Hi Marc! You are 23 years old</positiveCheck>
        <negativeCheck>(E|e)rror</negativeCheck>
        </command>
      </group>
    </body>
<tail></tail>
  </test>
  
    <test id="test4" name="A small mass test" timeout="20">
<head>
</head>
    <body>
      <group parallel="5" serial="5" id="1" name="jattetest">
        <command id="2" name="JATTATester aufrufen">
        <path>java -cp "..\JATTATester\build\classes" jattatester.JattaTester</path>
        <inputData>y</inputData>
        <inputData>Marc</inputData>
		<inputData>23</inputData>
		<positiveCheck>Hi Marc! You are 23 years old</positiveCheck>
        <negativeCheck>(E|e)rror</negativeCheck>
        </command>
      </group>
    </body>
<tail></tail>
  </test>
 
</testlist>

=== Erkan-Yilmaz/just-another-tool-for-test-automation/example_linux/successTest_linux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
#Just Another Tool for Test Automation
#Copyright (C) 2011  Marc Nesello
#
#This file is part of Just Another Tool for Test Automation.
#
#Just Another Tool for Test Automation is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<testlist name="Beispieltest" timeout="0" logfile="successTest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jatta.xsd">
<test id="t0" name="Simpler Test" timeout="0">
    <head>
      <group parallel="1" serial="1" id="1" name="head">
      	  <command id="0" name="Testverzeichnis erstellen">
	        <path>mkdir test</path>
	        <positiveCheck></positiveCheck>
	      </command>
	      <command id="1" name="Testdatei erstellen">
	        <path>touch test.txt</path>
	        <positiveCheck></positiveCheck>
	      </command>
	      <command id="2" name="Alte Testdatei löschen">
	        <path>rm test/test.txt</path>
	        <positiveCheck></positiveCheck>
	      </command>
      </group>
    </head>
    <body>
      <group parallel="1" serial="1" id="2" name="body">
        <command id="3" name="Sicherstellen dass Datei im Verzeichnis ist">
        <path>ls</path>
        <positiveCheck>test.txt</positiveCheck>
        </command>
        <command id="4" name="Sicherstellen dass Datei nicht im Verzeichnis ist">
        <path>ls test</path>
        <negativeCheck>test.txt</negativeCheck>
        </command>
        <command id="5" name="Datei kopieren">
          <path>cp test.txt test/test.txt</path>
          <positiveCheck></positiveCheck>
      	</command>
      	<command id="6" name="Prüfen ob Datei kopiert wurde">
        	<path>ls test</path>
        	<positiveCheck>test.txt</positiveCheck>
      	</command>
      	<command id="7" name="Prüfen ob Datei im alten Verzeichnis vorhanden ist">
      		<path>ls</path>
        	<positiveCheck>test.txt</positiveCheck>
      	</command>
      </group>
    </body>
    <tail>
    	<group parallel="1" serial="1" id="3" name="tail">
      	<command id="8" name="Testdatei löschen im alten Verzeichnis">
        	<path>rm test.txt</path>
        	<positiveCheck></positiveCheck>
      	</command>
      	<command id="9" name="Testdatei löschen im neuen Verzeichnis">
        	<path>rm -i test/test.txt</path>
        	<positiveCheck></positiveCheck>
			<inputData>y</inputData>
      	</command>
      	<command id="10" name="Testdatei löschen">
        	<path>rmdir test</path>
        	<positiveCheck></positiveCheck>
      	</command>
      </group>
    </tail>  
  </test>
</testlist>

=== Erkan-Yilmaz/just-another-tool-for-test-automation/example_win/cpanp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
#Just Another Tool for Test Automation
#Copyright (C) 2011  Marc Nesello
#
#This file is part of Just Another Tool for Test Automation.
#
#Just Another Tool for Test Automation is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<testlist name="Test cpanp" timeout="500" logfile="cpanp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jatta.xsd">
<test id="t0" name="Install perl module xml::simple with cpanp" timeout="300">
    <head>
    </head>
    <body>
      <group id="1" name="install module">
        <command id="3" name="Call cpanp and install module">
        	<path>cpanp i XML::Simple</path>
        	<positiveCheck>No errors installing all modules</positiveCheck>
		<positiveCheck>Module 'XML::Simple' installed successfully</positiveCheck>
		<negativeCheck>ERROR</negativeCheck>
        </command>
      </group>
    </body>
    <tail>
    </tail>  
  </test>
 <test id="t1" name="Uninstall perl module xml::simple with cpanp" timeout="300">
    <head>
    </head>
    <body>
      <group id="1" name="uninstall module">
        <command id="3" name="Call cpanp and uninstall module">
		<!--Ein Kommentar: Blabla-->
        	<path>cpanp u XML::Simple --force</path>
        	<positiveCheck>Module 'XML::Simple' uninstalled successfully</positiveCheck>
		<positiveCheck>All modules uninstalled successfully</positiveCheck>
		<negativeCheck>ERROR</negativeCheck>
        </command>
      </group>
    </body>
    <tail>
    </tail>  
  </test>
</testlist>

=== Erkan-Yilmaz/just-another-tool-for-test-automation/example_linux/runTester_linux.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
#Just Another Tool for Test Automation
#Copyright (C) 2011  Marc Nesello
#
#This file is part of Just Another Tool for Test Automation.
#
#Just Another Tool for Test Automation is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<testlist name="Beispieltest" timeout="0" logfile="runTester" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jatta.xsd">
<test id="test1" name="Provoke Error" timeout="0">
<head>
</head>
    <body>
      <group parallel="1" serial="1" id="1" name="jattetest">
        <command id="1" name="JATTATester aufrufen">
        <path>java -cp ../JATTATester/build/classes jattatester.JattaTester</path>
        <inputData>n</inputData>
        <inputData></inputData>
        <negativeCheck>(E|e)rror</negativeCheck>
        </command>
      </group>
    </body>
<tail></tail>
  </test>
  <test id="test2" name="App sleeps, use timeout" timeout="10">
<head>
</head>
    <body>
      <group parallel="1" serial="1" id="1" name="jattetest">
        <command id="2" name="JATTATester aufrufen">
        <path>java -cp ../JATTATester/build/classes jattatester.JattaTester</path>
        <inputData>n</inputData>
        <inputData>sleep</inputData>
		<inputData>1000</inputData>
        <negativeCheck>(E|e)rror</negativeCheck>
        </command>
      </group>
    </body>
<tail></tail>
  </test>
  <test id="test3" name="App with some input" timeout="10">
<head>
</head>
    <body>
      <group parallel="1" serial="1" id="1" name="jattetest">
        <command id="3" name="JATTATester aufrufen">
        <path>java -cp ../JATTATester/build/classes jattatester.JattaTester</path>
        <inputData>y</inputData>
        <inputData>Marc</inputData>
		<inputData>23</inputData>
		<positiveCheck>Hi Marc! You are 23 years old</positiveCheck>
        <negativeCheck>(E|e)rror</negativeCheck>
        </command>
      </group>
    </body>
<tail></tail>
  </test>
 
</testlist>

=== Erkan-Yilmaz/just-another-tool-for-test-automation/example_linux/aptsh.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
#Just Another Tool for Test Automation
#Copyright (C) 2011  Marc Nesello
#
#This file is part of Just Another Tool for Test Automation.
#
#Just Another Tool for Test Automation is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 2 of the License, or
#(at your option) any later version.

#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.

#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->
<testlist name="Try to install ksh and uninstall it with aptsh" timeout="500" logfile="aptsh" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="jatta.xsd">
<test id="test1" name="Install ksh" timeout="0">
<head>
</head>
    <body>
      <group parallel="1" serial="1" id="1" name="Install ksh">
        <command id="0" name="Check if ksh is installed">
       		<path>apt-cache policy ksh</path>
		<positiveCheck>Installiert: \(keine\)</positiveCheck>
        	<negativeCheck>(E|e)rror</negativeCheck>
        </command>
        <command id="1" name="Call aptsh and install ksh">
        	<path>aptsh</path>
        	<inputData>install ksh</inputData>
        	<inputData>quit</inputData>
		<positiveCheck>Richte ksh ein</positiveCheck>
        	<negativeCheck>(E|e)rror</negativeCheck>
        </command>
        <command id="2" name="Check if ksh is installed">
        	<path>apt-cache policy ksh</path>
		<positiveCheck>Installiert: \d+</positiveCheck>
        	<negativeCheck>(E|e)rror</negativeCheck>
        </command>

      </group>
    </body>
<tail></tail>
  </test>
<test id="test2" name="Uninstall ksh" timeout="0">
<head>
</head>
    <body>
      <group parallel="1" serial="1" id="1" name="Uninstall ksh">
        <command id="0" name="Check if ksh is installed">
       		<path>apt-cache policy ksh</path>
		<positiveCheck>Installiert: \d+</positiveCheck>
        	<negativeCheck>(E|e)rror</negativeCheck>
        </command>
        <command id="1" name="Call aptsh and uninstall ksh">
        	<path>aptsh</path>
        	<inputData>remove ksh</inputData>
        	<inputData>J</inputData>
        	<inputData>quit</inputData>
		<positiveCheck>Entferne ksh</positiveCheck>
        	<negativeCheck>(E|e)rror</negativeCheck>
        </command>
        <command id="2" name="Check if ksh is installed">
        	<path>apt-cache policy ksh</path>
		<positiveCheck>Installiert: \(keine\)</positiveCheck>
        	<negativeCheck>(E|e)rror</negativeCheck>
        </command>
      </group>
    </body>
<tail></tail>
  </test>
 
</testlist>
